name: Lumos Testing

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.py'

jobs:
  Lumos-Testing-on-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Install lumos as a development package
        run: |
          python setup.py develop
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run tests with pytest
        run: |
          pytest -vs
  
  Lumos-Testing-on-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install lumos dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .\requirements.txt
      - name: Install lumos as a development package
        run: |
          python setup.py develop
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run tests with pytest
        run: |
          pytest -vs
