name: Lumos Testing

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.py'
      - '**.yaml'

jobs:
  Lumos-Testing:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04,windows-latest]
        python-version: ["3.8", "3.9","3.10"]
    runs-on: ${{ matrix.os }}
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Install lumos as a development package
        run: |
          python setup.py develop
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run tests with pytest
        run: |
          pytest -vs
